//! Bulk operations for AssetDepreciationEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateAssetDepreciationEntryDto;
use crate::application::service::AssetDepreciationEntryService;
use crate::domain::entity::AssetDepreciationEntry;

/// Bulk operation handler for AssetDepreciationEntry entities.
///
/// Wraps `AssetDepreciationEntryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type AssetDepreciationEntryBulkService = GenericBulkService<AssetDepreciationEntry, CreateAssetDepreciationEntryDto, AssetDepreciationEntryService>;

// <<< CUSTOM
// END CUSTOM
