//! Bulk operations for AssetCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateAssetCategoryDto;
use crate::application::service::AssetCategoryService;
use crate::domain::entity::AssetCategory;

/// Bulk operation handler for AssetCategory entities.
///
/// Wraps `AssetCategoryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type AssetCategoryBulkService = GenericBulkService<AssetCategory, CreateAssetCategoryDto, AssetCategoryService>;

// <<< CUSTOM
// END CUSTOM
