//! Bulk operations for Asset entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateAssetDto;
use crate::application::service::AssetService;
use crate::domain::entity::Asset;

/// Bulk operation handler for Asset entities.
///
/// Wraps `AssetService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type AssetBulkService = GenericBulkService<Asset, CreateAssetDto, AssetService>;

// <<< CUSTOM
// END CUSTOM
