//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod asset_category_bulk;
pub mod asset_bulk;
pub mod asset_depreciation_entry_bulk;

pub use asset_category_bulk::AssetCategoryBulkService;
pub use asset_bulk::AssetBulkService;
pub use asset_depreciation_entry_bulk::AssetDepreciationEntryBulkService;

// <<< CUSTOM
// END CUSTOM
