//! AssetCategory DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AssetCategory;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::DepreciationMethod;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AssetCategory
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAssetCategoryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "category_name")]
    pub category_name: String,
    #[serde(alias = "depreciation_method")]
    pub depreciation_method: DepreciationMethod,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "useful_life_months")]
    pub useful_life_months: i32,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "fixed_asset_account_id")]
    pub fixed_asset_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "accumulated_depreciation_account_id")]
    pub accumulated_depreciation_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "depreciation_expense_account_id")]
    pub depreciation_expense_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "disposal_gain_loss_account_id")]
    pub disposal_gain_loss_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AssetCategory
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAssetCategoryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "category_name")]
    pub category_name: String,
    #[serde(alias = "depreciation_method")]
    pub depreciation_method: DepreciationMethod,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "useful_life_months")]
    pub useful_life_months: i32,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "fixed_asset_account_id")]
    pub fixed_asset_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "accumulated_depreciation_account_id")]
    pub accumulated_depreciation_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "depreciation_expense_account_id")]
    pub depreciation_expense_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "disposal_gain_loss_account_id")]
    pub disposal_gain_loss_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AssetCategory
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAssetCategoryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "category_name")]
    pub category_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "depreciation_method")]
    pub depreciation_method: Option<DepreciationMethod>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "useful_life_months")]
    pub useful_life_months: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "fixed_asset_account_id")]
    pub fixed_asset_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "accumulated_depreciation_account_id")]
    pub accumulated_depreciation_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "depreciation_expense_account_id")]
    pub depreciation_expense_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "disposal_gain_loss_account_id")]
    pub disposal_gain_loss_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchAssetCategoryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.category_name.is_some() || self.depreciation_method.is_some() || self.useful_life_months.is_some() || self.fixed_asset_account_id.is_some() || self.accumulated_depreciation_account_id.is_some() || self.depreciation_expense_account_id.is_some() || self.disposal_gain_loss_account_id.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AssetCategory entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AssetCategoryResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub category_name: String,
    pub depreciation_method: DepreciationMethod,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub useful_life_months: i32,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub fixed_asset_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub accumulated_depreciation_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub depreciation_expense_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub disposal_gain_loss_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AssetCategory entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AssetCategoryListResponseDto {
    /// List of items
    pub items: Vec<AssetCategoryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AssetCategoryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AssetCategoryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AssetCategorySummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub category_name: String,
    pub depreciation_method: DepreciationMethod,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AssetCategory> for AssetCategoryResponseDto {
    fn from(entity: AssetCategory) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            category_name: entity.category_name,
            depreciation_method: entity.depreciation_method,
            useful_life_months: entity.useful_life_months,
            fixed_asset_account_id: entity.fixed_asset_account_id,
            accumulated_depreciation_account_id: entity.accumulated_depreciation_account_id,
            depreciation_expense_account_id: entity.depreciation_expense_account_id,
            disposal_gain_loss_account_id: entity.disposal_gain_loss_account_id,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<AssetCategory> for AssetCategorySummaryDto {
    fn from(entity: AssetCategory) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            category_name: entity.category_name,
            depreciation_method: entity.depreciation_method,
            created_at,
        }
    }
}

impl From<CreateAssetCategoryDto> for AssetCategory {
    fn from(dto: CreateAssetCategoryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            category_name: dto.category_name,
            depreciation_method: dto.depreciation_method,
            useful_life_months: dto.useful_life_months,
            fixed_asset_account_id: dto.fixed_asset_account_id,
            accumulated_depreciation_account_id: dto.accumulated_depreciation_account_id,
            depreciation_expense_account_id: dto.depreciation_expense_account_id,
            disposal_gain_loss_account_id: dto.disposal_gain_loss_account_id,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AssetCategory> for AssetCategoryResponseDto {
    fn from(entity: &AssetCategory) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            category_name: entity.category_name.clone(),
            depreciation_method: entity.depreciation_method.clone(),
            useful_life_months: entity.useful_life_months.clone(),
            fixed_asset_account_id: entity.fixed_asset_account_id.clone(),
            accumulated_depreciation_account_id: entity.accumulated_depreciation_account_id.clone(),
            depreciation_expense_account_id: entity.depreciation_expense_account_id.clone(),
            disposal_gain_loss_account_id: entity.disposal_gain_loss_account_id.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAssetCategoryDto> for AssetCategory {
    fn from_create_dto(dto: CreateAssetCategoryDto) -> backbone_core::ServiceResult<Self> {
        Ok(AssetCategory::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAssetCategoryDto> for AssetCategory {
    fn apply_update(mut self, dto: UpdateAssetCategoryDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.category_name = dto.category_name;
        self.depreciation_method = dto.depreciation_method;
        self.useful_life_months = dto.useful_life_months;
        self.fixed_asset_account_id = dto.fixed_asset_account_id;
        self.accumulated_depreciation_account_id = dto.accumulated_depreciation_account_id;
        self.depreciation_expense_account_id = dto.depreciation_expense_account_id;
        self.disposal_gain_loss_account_id = dto.disposal_gain_loss_account_id;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AssetCategory here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
