//! Asset DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Asset;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::AssetStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Asset
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAssetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "asset_category_id")]
    pub asset_category_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "asset_name")]
    pub asset_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "asset_code")]
    pub asset_code: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[serde(alias = "gross_purchase_amount")]
    pub gross_purchase_amount: Decimal,
    #[serde(alias = "salvage_value")]
    pub salvage_value: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "useful_life_months")]
    pub useful_life_months: i32,
    #[serde(alias = "opening_accumulated_depreciation")]
    pub opening_accumulated_depreciation: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "purchase_date")]
    pub purchase_date: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "available_for_use_date")]
    pub available_for_use_date: Option<DateTime<Utc>>,
    #[serde(alias = "accumulated_depreciation")]
    pub accumulated_depreciation: Decimal,
    #[serde(alias = "net_book_value")]
    pub net_book_value: Decimal,
    pub status: AssetStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Asset
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAssetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "asset_category_id")]
    pub asset_category_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "asset_name")]
    pub asset_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "asset_code")]
    pub asset_code: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[serde(alias = "gross_purchase_amount")]
    pub gross_purchase_amount: Decimal,
    #[serde(alias = "salvage_value")]
    pub salvage_value: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "useful_life_months")]
    pub useful_life_months: i32,
    #[serde(alias = "opening_accumulated_depreciation")]
    pub opening_accumulated_depreciation: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "purchase_date")]
    pub purchase_date: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "available_for_use_date")]
    pub available_for_use_date: Option<DateTime<Utc>>,
    #[serde(alias = "accumulated_depreciation")]
    pub accumulated_depreciation: Decimal,
    #[serde(alias = "net_book_value")]
    pub net_book_value: Decimal,
    pub status: AssetStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Asset
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAssetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "asset_category_id")]
    pub asset_category_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "asset_name")]
    pub asset_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "asset_code")]
    pub asset_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "gross_purchase_amount")]
    pub gross_purchase_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "salvage_value")]
    pub salvage_value: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "useful_life_months")]
    pub useful_life_months: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "opening_accumulated_depreciation")]
    pub opening_accumulated_depreciation: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "purchase_date")]
    pub purchase_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "available_for_use_date")]
    pub available_for_use_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "accumulated_depreciation")]
    pub accumulated_depreciation: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "net_book_value")]
    pub net_book_value: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<AssetStatus>,
}

impl PatchAssetDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.asset_category_id.is_some() || self.asset_name.is_some() || self.asset_code.is_some() || self.item_id.is_some() || self.branch_id.is_some() || self.gross_purchase_amount.is_some() || self.salvage_value.is_some() || self.useful_life_months.is_some() || self.opening_accumulated_depreciation.is_some() || self.purchase_date.is_some() || self.available_for_use_date.is_some() || self.accumulated_depreciation.is_some() || self.net_book_value.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Asset entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AssetResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub asset_category_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub asset_name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub asset_code: String,
    pub item_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub gross_purchase_amount: Decimal,
    pub salvage_value: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub useful_life_months: i32,
    pub opening_accumulated_depreciation: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub purchase_date: DateTime<Utc>,
    pub available_for_use_date: Option<DateTime<Utc>>,
    pub accumulated_depreciation: Decimal,
    pub net_book_value: Decimal,
    pub status: AssetStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Asset entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AssetListResponseDto {
    /// List of items
    pub items: Vec<AssetResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AssetListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AssetResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AssetSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub asset_category_id: Uuid,
    pub asset_name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Asset> for AssetResponseDto {
    fn from(entity: Asset) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            asset_category_id: entity.asset_category_id,
            asset_name: entity.asset_name,
            asset_code: entity.asset_code,
            item_id: entity.item_id,
            branch_id: entity.branch_id,
            gross_purchase_amount: entity.gross_purchase_amount,
            salvage_value: entity.salvage_value,
            useful_life_months: entity.useful_life_months,
            opening_accumulated_depreciation: entity.opening_accumulated_depreciation,
            purchase_date: entity.purchase_date,
            available_for_use_date: entity.available_for_use_date,
            accumulated_depreciation: entity.accumulated_depreciation,
            net_book_value: entity.net_book_value,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<Asset> for AssetSummaryDto {
    fn from(entity: Asset) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            asset_category_id: entity.asset_category_id,
            asset_name: entity.asset_name,
            created_at,
        }
    }
}

impl From<CreateAssetDto> for Asset {
    fn from(dto: CreateAssetDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            asset_category_id: dto.asset_category_id,
            asset_name: dto.asset_name,
            asset_code: dto.asset_code,
            item_id: dto.item_id,
            branch_id: dto.branch_id,
            gross_purchase_amount: dto.gross_purchase_amount,
            salvage_value: dto.salvage_value,
            useful_life_months: dto.useful_life_months,
            opening_accumulated_depreciation: dto.opening_accumulated_depreciation,
            purchase_date: dto.purchase_date,
            available_for_use_date: dto.available_for_use_date,
            accumulated_depreciation: dto.accumulated_depreciation,
            net_book_value: dto.net_book_value,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Asset> for AssetResponseDto {
    fn from(entity: &Asset) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            asset_category_id: entity.asset_category_id.clone(),
            asset_name: entity.asset_name.clone(),
            asset_code: entity.asset_code.clone(),
            item_id: entity.item_id.clone(),
            branch_id: entity.branch_id.clone(),
            gross_purchase_amount: entity.gross_purchase_amount.clone(),
            salvage_value: entity.salvage_value.clone(),
            useful_life_months: entity.useful_life_months.clone(),
            opening_accumulated_depreciation: entity.opening_accumulated_depreciation.clone(),
            purchase_date: entity.purchase_date.clone(),
            available_for_use_date: entity.available_for_use_date.clone(),
            accumulated_depreciation: entity.accumulated_depreciation.clone(),
            net_book_value: entity.net_book_value.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAssetDto> for Asset {
    fn from_create_dto(dto: CreateAssetDto) -> backbone_core::ServiceResult<Self> {
        Ok(Asset::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAssetDto> for Asset {
    fn apply_update(mut self, dto: UpdateAssetDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.asset_category_id = dto.asset_category_id;
        self.asset_name = dto.asset_name;
        self.asset_code = dto.asset_code;
        self.item_id = dto.item_id;
        self.branch_id = dto.branch_id;
        self.gross_purchase_amount = dto.gross_purchase_amount;
        self.salvage_value = dto.salvage_value;
        self.useful_life_months = dto.useful_life_months;
        self.opening_accumulated_depreciation = dto.opening_accumulated_depreciation;
        self.purchase_date = dto.purchase_date;
        self.available_for_use_date = dto.available_for_use_date;
        self.accumulated_depreciation = dto.accumulated_depreciation;
        self.net_book_value = dto.net_book_value;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Asset here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
