//! AssetDepreciationEntry DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AssetDepreciationEntry;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AssetDepreciationEntry
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAssetDepreciationEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "asset_id")]
    pub asset_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "period_no")]
    pub period_no: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "schedule_date")]
    pub schedule_date: DateTime<Utc>,
    #[serde(alias = "depreciation_amount")]
    pub depreciation_amount: Decimal,
    #[serde(alias = "accumulated_after")]
    pub accumulated_after: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub posted: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AssetDepreciationEntry
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAssetDepreciationEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "asset_id")]
    pub asset_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "period_no")]
    pub period_no: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "schedule_date")]
    pub schedule_date: DateTime<Utc>,
    #[serde(alias = "depreciation_amount")]
    pub depreciation_amount: Decimal,
    #[serde(alias = "accumulated_after")]
    pub accumulated_after: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub posted: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AssetDepreciationEntry
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAssetDepreciationEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "asset_id")]
    pub asset_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "period_no")]
    pub period_no: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "schedule_date")]
    pub schedule_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "depreciation_amount")]
    pub depreciation_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "accumulated_after")]
    pub accumulated_after: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub posted: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
}

impl PatchAssetDepreciationEntryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.asset_id.is_some() || self.period_no.is_some() || self.schedule_date.is_some() || self.depreciation_amount.is_some() || self.accumulated_after.is_some() || self.posted.is_some() || self.posted_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AssetDepreciationEntry entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AssetDepreciationEntryResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub asset_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub period_no: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub schedule_date: DateTime<Utc>,
    pub depreciation_amount: Decimal,
    pub accumulated_after: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub posted: bool,
    pub posted_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AssetDepreciationEntry entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AssetDepreciationEntryListResponseDto {
    /// List of items
    pub items: Vec<AssetDepreciationEntryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AssetDepreciationEntryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AssetDepreciationEntryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AssetDepreciationEntrySummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub asset_id: Uuid,
    pub period_no: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AssetDepreciationEntry> for AssetDepreciationEntryResponseDto {
    fn from(entity: AssetDepreciationEntry) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            asset_id: entity.asset_id,
            period_no: entity.period_no,
            schedule_date: entity.schedule_date,
            depreciation_amount: entity.depreciation_amount,
            accumulated_after: entity.accumulated_after,
            posted: entity.posted,
            posted_at: entity.posted_at,
            metadata: entity.metadata,
        }
    }
}

impl From<AssetDepreciationEntry> for AssetDepreciationEntrySummaryDto {
    fn from(entity: AssetDepreciationEntry) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            asset_id: entity.asset_id,
            period_no: entity.period_no,
            created_at,
        }
    }
}

impl From<CreateAssetDepreciationEntryDto> for AssetDepreciationEntry {
    fn from(dto: CreateAssetDepreciationEntryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            asset_id: dto.asset_id,
            period_no: dto.period_no,
            schedule_date: dto.schedule_date,
            depreciation_amount: dto.depreciation_amount,
            accumulated_after: dto.accumulated_after,
            posted: dto.posted,
            posted_at: dto.posted_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AssetDepreciationEntry> for AssetDepreciationEntryResponseDto {
    fn from(entity: &AssetDepreciationEntry) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            asset_id: entity.asset_id.clone(),
            period_no: entity.period_no.clone(),
            schedule_date: entity.schedule_date.clone(),
            depreciation_amount: entity.depreciation_amount.clone(),
            accumulated_after: entity.accumulated_after.clone(),
            posted: entity.posted.clone(),
            posted_at: entity.posted_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAssetDepreciationEntryDto> for AssetDepreciationEntry {
    fn from_create_dto(dto: CreateAssetDepreciationEntryDto) -> backbone_core::ServiceResult<Self> {
        Ok(AssetDepreciationEntry::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAssetDepreciationEntryDto> for AssetDepreciationEntry {
    fn apply_update(mut self, dto: UpdateAssetDepreciationEntryDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.asset_id = dto.asset_id;
        self.period_no = dto.period_no;
        self.schedule_date = dto.schedule_date;
        self.depreciation_amount = dto.depreciation_amount;
        self.accumulated_after = dto.accumulated_after;
        self.posted = dto.posted;
        self.posted_at = dto.posted_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AssetDepreciationEntry here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
