//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod asset_category_specification;
pub mod asset_specification;
pub mod asset_depreciation_entry_specification;

// <<< CUSTOM
// END CUSTOM
