//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod asset_category_domain_policy;
pub mod asset_domain_policy;
pub mod asset_depreciation_entry_domain_policy;

pub use asset_category_domain_policy::AssetCategoryDomainPolicy;
pub use asset_domain_policy::AssetDomainPolicy;
pub use asset_depreciation_entry_domain_policy::AssetDepreciationEntryDomainPolicy;

// <<< CUSTOM
// END CUSTOM
