//! Application service for Asset entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `asset_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAssetDto, UpdateAssetDto};
use crate::domain::entity::Asset;
use crate::infrastructure::persistence::AssetRepository;

/// Application service for Asset entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `asset_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AssetServiceCustom {
///     inner: Arc<AssetService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AssetService = GenericCrudService<
    Asset,
    CreateAssetDto,
    UpdateAssetDto,
    AssetRepository,
>;

// <<< CUSTOM
// END CUSTOM
