//! Application service for AssetCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `asset_category_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAssetCategoryDto, UpdateAssetCategoryDto};
use crate::domain::entity::AssetCategory;
use crate::infrastructure::persistence::AssetCategoryRepository;

/// Application service for AssetCategory entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `asset_category_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AssetCategoryServiceCustom {
///     inner: Arc<AssetCategoryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AssetCategoryService = GenericCrudService<
    AssetCategory,
    CreateAssetCategoryDto,
    UpdateAssetCategoryDto,
    AssetCategoryRepository,
>;

// <<< CUSTOM
// END CUSTOM
