//! Application service for AssetDepreciationEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `asset_depreciation_entry_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAssetDepreciationEntryDto, UpdateAssetDepreciationEntryDto};
use crate::domain::entity::AssetDepreciationEntry;
use crate::infrastructure::persistence::AssetDepreciationEntryRepository;

/// Application service for AssetDepreciationEntry entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `asset_depreciation_entry_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AssetDepreciationEntryServiceCustom {
///     inner: Arc<AssetDepreciationEntryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AssetDepreciationEntryService = GenericCrudService<
    AssetDepreciationEntry,
    CreateAssetDepreciationEntryDto,
    UpdateAssetDepreciationEntryDto,
    AssetDepreciationEntryRepository,
>;

// <<< CUSTOM
// END CUSTOM
