//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod asset_category_service;
pub mod asset_service;
pub mod asset_depreciation_entry_service;

// <<< CUSTOM
pub mod asset_gl;
pub mod asset_events;
pub mod asset_write_service;
// END CUSTOM

pub use asset_category_service::AssetCategoryService;
pub use asset_service::AssetService;
pub use asset_depreciation_entry_service::AssetDepreciationEntryService;
// <<< CUSTOM
pub use asset_gl::{
    AccountingPostEnvelope, GlPostAck, GlPostLine, GlPostRejected, GlPostSink,
};
pub use asset_events::{
    AssetActivated, AssetDisposed, AssetEvent, AssetEventSink, DepreciationPosted, LoggingSink,
};
pub use asset_write_service::{
    AssetError, AssetWriteService, DepreciationRunOutcome, DisposalOutcome, NewAsset,
    NewAssetCategory,
};
// END CUSTOM