-- AssetDepreciationEntry Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the asset.asset_depreciation_entries table.
-- Customize this file to add your initial data.

-- INSERT INTO asset.asset_depreciation_entries (
--     id,
--     company_id,
--     asset_id,
--     period_no,
--     schedule_date,
--     depreciation_amount,
--     accumulated_after,
--     posted,
--     posted_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO asset.asset_depreciation_entries (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

