-- Asset Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the asset.assets table.
-- Customize this file to add your initial data.

-- INSERT INTO asset.assets (
--     id,
--     company_id,
--     asset_category_id,
--     asset_name,
--     asset_code,
--     item_id,
--     branch_id,
--     gross_purchase_amount,
--     salvage_value,
--     useful_life_months,
--     opening_accumulated_depreciation,
--     purchase_date,
--     available_for_use_date,
--     accumulated_depreciation,
--     net_book_value,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO asset.assets (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

