-- Migration: Create asset_categories table
-- Generated by metaphor-schema

-- Create depreciation_method enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'depreciation_method') THEN
        CREATE TYPE depreciation_method AS ENUM ('straight_line', 'declining_balance', 'written_down_value');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS asset;

CREATE TABLE IF NOT EXISTS asset.asset_categories (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    category_name TEXT NOT NULL,
    depreciation_method depreciation_method NOT NULL DEFAULT 'straight_line',
    useful_life_months INTEGER NOT NULL,
    fixed_asset_account_id UUID NOT NULL,
    accumulated_depreciation_account_id UUID NOT NULL,
    depreciation_expense_account_id UUID NOT NULL,
    disposal_gain_loss_account_id UUID NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_asset_categories_company_id_is_active ON asset.asset_categories (company_id, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_asset_categories_metadata_gin ON asset.asset_categories USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_asset_categories_metadata_deleted_at ON asset.asset_categories ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_asset_categories_metadata_created_at ON asset.asset_categories ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_asset_categories_metadata_updated_at ON asset.asset_categories ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION asset.asset_categories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS asset_categories_insert_audit ON asset.asset_categories;
CREATE TRIGGER asset_categories_insert_audit BEFORE INSERT ON asset.asset_categories
    FOR EACH ROW EXECUTE FUNCTION asset.asset_categories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS asset_categories_update_audit ON asset.asset_categories;
CREATE TRIGGER asset_categories_update_audit BEFORE UPDATE ON asset.asset_categories
    FOR EACH ROW EXECUTE FUNCTION asset.asset_categories_audit_timestamp();
