-- Company RLS fence for assets module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for asset.asset_categories
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE asset.asset_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset.asset_categories FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS asset_categories_company_isolation ON asset.asset_categories;
CREATE POLICY asset_categories_company_isolation ON asset.asset_categories
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for asset.assets
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE asset.assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset.assets FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS assets_company_isolation ON asset.assets;
CREATE POLICY assets_company_isolation ON asset.assets
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for asset.asset_depreciation_entries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE asset.asset_depreciation_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset.asset_depreciation_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS asset_depreciation_entries_company_isolation ON asset.asset_depreciation_entries;
CREATE POLICY asset_depreciation_entries_company_isolation ON asset.asset_depreciation_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

