-- Audit Triggers Migration for assets module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: AssetCategory (asset.asset_categories)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION asset.asset_categories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS asset_categories_insert_audit ON asset.asset_categories;
CREATE TRIGGER asset_categories_insert_audit BEFORE INSERT ON asset.asset_categories
    FOR EACH ROW EXECUTE FUNCTION asset.asset_categories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS asset_categories_update_audit ON asset.asset_categories;
CREATE TRIGGER asset_categories_update_audit BEFORE UPDATE ON asset.asset_categories
    FOR EACH ROW EXECUTE FUNCTION asset.asset_categories_audit_timestamp();

-- ==============================================================================
-- Table: Asset (asset.assets)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION asset.assets_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS assets_insert_audit ON asset.assets;
CREATE TRIGGER assets_insert_audit BEFORE INSERT ON asset.assets
    FOR EACH ROW EXECUTE FUNCTION asset.assets_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS assets_update_audit ON asset.assets;
CREATE TRIGGER assets_update_audit BEFORE UPDATE ON asset.assets
    FOR EACH ROW EXECUTE FUNCTION asset.assets_audit_timestamp();

-- ==============================================================================
-- Table: AssetDepreciationEntry (asset.asset_depreciation_entries)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION asset.asset_depreciation_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS asset_depreciation_entries_insert_audit ON asset.asset_depreciation_entries;
CREATE TRIGGER asset_depreciation_entries_insert_audit BEFORE INSERT ON asset.asset_depreciation_entries
    FOR EACH ROW EXECUTE FUNCTION asset.asset_depreciation_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS asset_depreciation_entries_update_audit ON asset.asset_depreciation_entries;
CREATE TRIGGER asset_depreciation_entries_update_audit BEFORE UPDATE ON asset.asset_depreciation_entries
    FOR EACH ROW EXECUTE FUNCTION asset.asset_depreciation_entries_audit_timestamp();

