-- Enum types for assets module
-- Generated by metaphor-schema

-- Create depreciation_method enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'depreciation_method') THEN
        CREATE TYPE depreciation_method AS ENUM ('straight_line', 'declining_balance', 'written_down_value');
    END IF;
END
$$;

-- Create asset_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'asset_status') THEN
        CREATE TYPE asset_status AS ENUM ('draft', 'active', 'fully_depreciated', 'disposed');
    END IF;
END
$$;

