-- Migration: Create asset_depreciation_entries table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS asset;

CREATE TABLE IF NOT EXISTS asset.asset_depreciation_entries (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    asset_id UUID NOT NULL,
    period_no INTEGER NOT NULL,
    schedule_date TIMESTAMPTZ NOT NULL,
    depreciation_amount NUMERIC(18, 2) NOT NULL CHECK (depreciation_amount >= 0),
    accumulated_after NUMERIC(18, 2) NOT NULL CHECK (accumulated_after >= 0),
    posted BOOLEAN NOT NULL DEFAULT FALSE,
    posted_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_asset_depreciation_entries_asset_id_period_no ON asset.asset_depreciation_entries (asset_id, period_no) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_asset_depreciation_entries_company_id_asset_id_posted ON asset.asset_depreciation_entries (company_id, asset_id, posted);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_asset_depreciation_entries_metadata_gin ON asset.asset_depreciation_entries USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_asset_depreciation_entries_metadata_deleted_at ON asset.asset_depreciation_entries ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_asset_depreciation_entries_metadata_created_at ON asset.asset_depreciation_entries ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_asset_depreciation_entries_metadata_updated_at ON asset.asset_depreciation_entries ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION asset.asset_depreciation_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS asset_depreciation_entries_insert_audit ON asset.asset_depreciation_entries;
CREATE TRIGGER asset_depreciation_entries_insert_audit BEFORE INSERT ON asset.asset_depreciation_entries
    FOR EACH ROW EXECUTE FUNCTION asset.asset_depreciation_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS asset_depreciation_entries_update_audit ON asset.asset_depreciation_entries;
CREATE TRIGGER asset_depreciation_entries_update_audit BEFORE UPDATE ON asset.asset_depreciation_entries
    FOR EACH ROW EXECUTE FUNCTION asset.asset_depreciation_entries_audit_timestamp();
