-- Migration: Create assets table
-- Generated by metaphor-schema

-- Create asset_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'asset_status') THEN
        CREATE TYPE asset_status AS ENUM ('draft', 'active', 'fully_depreciated', 'disposed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS asset;

CREATE TABLE IF NOT EXISTS asset.assets (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    asset_category_id UUID NOT NULL,
    asset_name TEXT NOT NULL,
    asset_code TEXT NOT NULL,
    item_id UUID,
    branch_id UUID,
    gross_purchase_amount NUMERIC NOT NULL,
    salvage_value NUMERIC NOT NULL DEFAULT 0,
    useful_life_months INTEGER NOT NULL,
    opening_accumulated_depreciation NUMERIC NOT NULL DEFAULT 0,
    purchase_date TIMESTAMPTZ NOT NULL,
    available_for_use_date TIMESTAMPTZ,
    accumulated_depreciation NUMERIC NOT NULL DEFAULT 0,
    net_book_value NUMERIC NOT NULL DEFAULT 0,
    status asset_status NOT NULL DEFAULT 'draft',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_assets_company_id_asset_code ON asset.assets (company_id, asset_code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_assets_company_id_status ON asset.assets (company_id, status);

CREATE INDEX IF NOT EXISTS idx_assets_asset_category_id ON asset.assets (asset_category_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_assets_metadata_gin ON asset.assets USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_assets_metadata_deleted_at ON asset.assets ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_assets_metadata_created_at ON asset.assets ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_assets_metadata_updated_at ON asset.assets ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION asset.assets_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS assets_insert_audit ON asset.assets;
CREATE TRIGGER assets_insert_audit BEFORE INSERT ON asset.assets
    FOR EACH ROW EXECUTE FUNCTION asset.assets_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS assets_update_audit ON asset.assets;
CREATE TRIGGER assets_update_audit BEFORE UPDATE ON asset.assets
    FOR EACH ROW EXECUTE FUNCTION asset.assets_audit_timestamp();
