//! Event handler trait for AssetDepreciationEntry events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AssetDepreciationEntryEvent;

/// Event handler for AssetDepreciationEntry events.
/// Implement this trait to react to AssetDepreciationEntry lifecycle events.
pub trait AssetDepreciationEntryEventHandler: EventHandler<AssetDepreciationEntryEvent> {}
