//! Domain events for Asset entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Asset;

/// Domain events for Asset — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Asset>)` variant.
pub type AssetEvent = CrudEvent<Asset>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Asset events.
pub type AssetEventPublisher = Arc<dyn CrudEventPublisher<Asset> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAssetEventPublisher = NoOpCrudEventPublisher<Asset>;
