//! Event handler trait for AssetCategory events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AssetCategoryEvent;

/// Event handler for AssetCategory events.
/// Implement this trait to react to AssetCategory lifecycle events.
pub trait AssetCategoryEventHandler: EventHandler<AssetCategoryEvent> {}
