//! Event handler trait for Asset events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AssetEvent;

/// Event handler for Asset events.
/// Implement this trait to react to Asset lifecycle events.
pub trait AssetEventHandler: EventHandler<AssetEvent> {}
