//! Domain events for AssetDepreciationEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AssetDepreciationEntry;

/// Domain events for AssetDepreciationEntry — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AssetDepreciationEntry>)` variant.
pub type AssetDepreciationEntryEvent = CrudEvent<AssetDepreciationEntry>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AssetDepreciationEntry events.
pub type AssetDepreciationEntryEventPublisher = Arc<dyn CrudEventPublisher<AssetDepreciationEntry> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAssetDepreciationEntryEventPublisher = NoOpCrudEventPublisher<AssetDepreciationEntry>;
