//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod asset_category_events;
pub mod asset_category_event_handlers;
pub mod asset_events;
pub mod asset_event_handlers;
pub mod asset_depreciation_entry_events;
pub mod asset_depreciation_entry_event_handlers;

pub use asset_category_events::{AssetCategoryEvent, AssetCategoryEventPublisher, NoopAssetCategoryEventPublisher};
pub use asset_category_event_handlers::AssetCategoryEventHandler;
pub use asset_events::{AssetEvent, AssetEventPublisher, NoopAssetEventPublisher};
pub use asset_event_handlers::AssetEventHandler;
pub use asset_depreciation_entry_events::{AssetDepreciationEntryEvent, AssetDepreciationEntryEventPublisher, NoopAssetDepreciationEntryEventPublisher};
pub use asset_depreciation_entry_event_handlers::AssetDepreciationEntryEventHandler;

// <<< CUSTOM
// END CUSTOM
