//! Event subscriber type aliases for Assets module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::AssetCategoryEvent;
use crate::domain::event::AssetEvent;
use crate::domain::event::AssetDepreciationEntryEvent;

/// Subscriber for AssetCategory events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type AssetCategoryEventSubscriber = GenericEventSubscriber<AssetCategoryEvent>;

/// Subscriber for Asset events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type AssetEventSubscriber = GenericEventSubscriber<AssetEvent>;

/// Subscriber for AssetDepreciationEntry events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type AssetDepreciationEntryEventSubscriber = GenericEventSubscriber<AssetDepreciationEntryEvent>;

// <<< CUSTOM
// END CUSTOM
