//! AssetDepreciationEntry seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial AssetDepreciationEntry data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ASSETDEPRECIATIONENTRY SEEDER
// ============================================================================

/// Seeder for asset_depreciation_entry
pub struct SeedAssetDepreciationEntrySeeder;

impl SeedAssetDepreciationEntrySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedAssetDepreciationEntrySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedAssetDepreciationEntrySeeder {
    fn name(&self) -> &'static str {
        "SeedAssetDepreciationEntrySeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if asset.asset_depreciation_entries table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM asset.asset_depreciation_entries")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/asset_depreciation_entry_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM asset.asset_depreciation_entries")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

