//! AssetCategory seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial AssetCategory data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ASSETCATEGORY SEEDER
// ============================================================================

/// Seeder for asset_category
pub struct SeedAssetCategorySeeder;

impl SeedAssetCategorySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedAssetCategorySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedAssetCategorySeeder {
    fn name(&self) -> &'static str {
        "SeedAssetCategorySeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if asset.asset_categories table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM asset.asset_categories")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/asset_category_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM asset.asset_categories")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

