//! Repository trait for AssetCategory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the AssetCategory aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{AssetCategory, DepreciationMethod};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AssetCategoryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AssetCategoryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AssetCategoryPaginatedResult {
    pub data: Vec<AssetCategory>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AssetCategoryFilter {
    pub company_id: Option<Uuid>,
    pub category_name: Option<String>,
    pub depreciation_method: Option<DepreciationMethod>,
    pub fixed_asset_account_id: Option<Uuid>,
    pub accumulated_depreciation_account_id: Option<Uuid>,
    pub depreciation_expense_account_id: Option<Uuid>,
    pub disposal_gain_loss_account_id: Option<Uuid>,
    pub is_active: Option<bool>,
}

impl AssetCategoryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.category_name.is_some() || self.depreciation_method.is_some() || self.fixed_asset_account_id.is_some() || self.accumulated_depreciation_account_id.is_some() || self.depreciation_expense_account_id.is_some() || self.disposal_gain_loss_account_id.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for AssetCategory aggregate
///
/// This trait defines the persistence contract for AssetCategory entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AssetCategoryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new asset_category entity
    async fn save(&self, entity: &AssetCategory) -> Result<AssetCategory>;

    /// Find asset_category by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<AssetCategory>>;

    /// Find all asset_category entities
    async fn find_all(&self) -> Result<Vec<AssetCategory>>;

    /// Update asset_category by ID
    async fn update(&self, id: &str, entity: &AssetCategory) -> Result<Option<AssetCategory>>;

    /// Delete asset_category by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List asset_category with pagination
    async fn list(&self, params: AssetCategoryPaginationParams) -> Result<AssetCategoryPaginatedResult>;

    /// List asset_category with pagination and filters
    async fn list_with_filters(&self, params: AssetCategoryPaginationParams, filters: AssetCategoryFilter) -> Result<AssetCategoryPaginatedResult>;

    /// Count all asset_category entities
    async fn count(&self) -> Result<u64>;

    /// Count asset_category entities matching filters
    async fn count_with_filters(&self, filters: AssetCategoryFilter) -> Result<u64>;

    /// Check if asset_category exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete asset_category by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted asset_category by ID
    async fn restore(&self, id: &str) -> Result<Option<AssetCategory>>;

    /// List soft-deleted asset_category entities
    async fn list_deleted(&self, params: AssetCategoryPaginationParams) -> Result<AssetCategoryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save asset_category entities
    async fn bulk_save(&self, entities: &[AssetCategory]) -> Result<Vec<AssetCategory>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
