//! Repository trait for Asset aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Asset aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Asset, AssetStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AssetPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AssetPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AssetPaginatedResult {
    pub data: Vec<Asset>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AssetFilter {
    pub company_id: Option<Uuid>,
    pub asset_category_id: Option<Uuid>,
    pub asset_name: Option<String>,
    pub asset_code: Option<String>,
    pub item_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub status: Option<AssetStatus>,
}

impl AssetFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.asset_category_id.is_some() || self.asset_name.is_some() || self.asset_code.is_some() || self.item_id.is_some() || self.branch_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for Asset aggregate
///
/// This trait defines the persistence contract for Asset entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AssetRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new asset entity
    async fn save(&self, entity: &Asset) -> Result<Asset>;

    /// Find asset by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Asset>>;

    /// Find all asset entities
    async fn find_all(&self) -> Result<Vec<Asset>>;

    /// Update asset by ID
    async fn update(&self, id: &str, entity: &Asset) -> Result<Option<Asset>>;

    /// Delete asset by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List asset with pagination
    async fn list(&self, params: AssetPaginationParams) -> Result<AssetPaginatedResult>;

    /// List asset with pagination and filters
    async fn list_with_filters(&self, params: AssetPaginationParams, filters: AssetFilter) -> Result<AssetPaginatedResult>;

    /// Count all asset entities
    async fn count(&self) -> Result<u64>;

    /// Count asset entities matching filters
    async fn count_with_filters(&self, filters: AssetFilter) -> Result<u64>;

    /// Check if asset exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete asset by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted asset by ID
    async fn restore(&self, id: &str) -> Result<Option<Asset>>;

    /// List soft-deleted asset entities
    async fn list_deleted(&self, params: AssetPaginationParams) -> Result<AssetPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save asset entities
    async fn bulk_save(&self, entities: &[Asset]) -> Result<Vec<Asset>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
