//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod asset_category_repository;
pub mod asset_repository;
pub mod asset_depreciation_entry_repository;

// Re-exports
pub use asset_category_repository::{
    AssetCategoryRepository,
    AssetCategoryPaginationParams,
    AssetCategoryPaginatedResult,
    AssetCategoryFilter,
};
pub use asset_repository::{
    AssetRepository,
    AssetPaginationParams,
    AssetPaginatedResult,
    AssetFilter,
};
pub use asset_depreciation_entry_repository::{
    AssetDepreciationEntryRepository,
    AssetDepreciationEntryPaginationParams,
    AssetDepreciationEntryPaginatedResult,
    AssetDepreciationEntryFilter,
};
