//! Repository for AssetCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AssetCategory, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::AssetCategory;

/// Table name for AssetCategory entities
pub const TABLE_NAME: &str = "asset.asset_categories";

/// Repository for AssetCategory entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AssetCategoryRepository(
    backbone_orm::GenericCrudRepository<AssetCategory, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AssetCategoryRepository {
    type Target = backbone_orm::GenericCrudRepository<AssetCategory, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AssetCategoryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(AssetCategoryRepository, AssetCategory, soft_delete);
