//! Repository for AssetCategory entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written AssetCategory SQL — the category definition and the account map every
//! GL post reads (4-layer rule: services orchestrate, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AssetCategory, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::AssetCategory;

/// Table name for AssetCategory entities
pub const TABLE_NAME: &str = "asset.asset_categories";

/// Repository for AssetCategory entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AssetCategoryRepository(
    backbone_orm::GenericCrudRepository<AssetCategory, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AssetCategoryRepository {
    type Target = backbone_orm::GenericCrudRepository<AssetCategory, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AssetCategoryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an asset-category definition writes.
///
/// Mirrors the raw column shape rather than the `AssetCategory` entity. `depreciation_method` is not a
/// field: the INSERT hard-codes `'straight_line'` — the only method wired.
pub struct NewAssetCategoryRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub category_name: &'a str,
    pub useful_life_months: i32,
    pub fixed_asset_account_id: Uuid,
    pub accumulated_depreciation_account_id: Uuid,
    pub depreciation_expense_account_id: Uuid,
    pub disposal_gain_loss_account_id: Uuid,
}

/// The category's method + account map — everything the lifecycle's GL posts need.
pub struct CategoryAccountsRow {
    pub method: String,
    pub useful_life_months: i32,
    pub fixed_asset_account_id: Uuid,
    pub accumulated_depreciation_account_id: Uuid,
    pub depreciation_expense_account_id: Uuid,
    pub disposal_gain_loss_account_id: Uuid,
}

/// Hand-written AssetCategory SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl AssetCategoryRepository {
    /// Define an asset category.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company is
    /// on the DTO, and that scope is what satisfies the INSERT's WITH CHECK fence. The explicit
    /// `company_id` bind stays as defense-in-depth.
    pub async fn insert_category(&self, pool: &PgPool, c: &NewAssetCategoryRow<'_>) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO asset.asset_categories
                     (id, company_id, category_name, depreciation_method, useful_life_months,
                      fixed_asset_account_id, accumulated_depreciation_account_id,
                      depreciation_expense_account_id, disposal_gain_loss_account_id, is_active)
                   VALUES ($1,$2,$3,'straight_line'::depreciation_method,$4,$5,$6,$7,$8,true)"#,
            )
            .bind(c.id).bind(c.company_id).bind(c.category_name).bind(c.useful_life_months)
            .bind(c.fixed_asset_account_id).bind(c.accumulated_depreciation_account_id)
            .bind(c.depreciation_expense_account_id).bind(c.disposal_gain_loss_account_id),
        )
        .await?;
        Ok(())
    }

    /// The category's default useful life — what a new asset snapshots when it doesn't override it.
    ///
    /// A read outside any transaction: takes the pool and runs `fetch_optional_scalar_scoped` so the RLS
    /// fence (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))`. The
    /// explicit `company_id = $2` filter stays as defense-in-depth.
    pub async fn find_useful_life(
        &self,
        pool: &PgPool,
        category_id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<i32>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"SELECT useful_life_months FROM asset.asset_categories
                   WHERE id=$1 AND company_id=$2 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(category_id)
            .bind(company_id),
        )
        .await
    }

    /// The category's method + account map.
    ///
    /// The company is a parameter (the caller read it off the asset row), so this is correct for
    /// non-request callers (the depreciation job) too — the caller wraps it in
    /// `with_company_scope(Some(company_id))`. The explicit `company_id = $2` filter stays as
    /// defense-in-depth.
    pub async fn find_accounts(
        &self,
        pool: &PgPool,
        category_id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<CategoryAccountsRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT depreciation_method::text AS method, useful_life_months,
                          fixed_asset_account_id, accumulated_depreciation_account_id,
                          depreciation_expense_account_id, disposal_gain_loss_account_id
                   FROM asset.asset_categories WHERE id=$1 AND company_id=$2 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(category_id)
            .bind(company_id),
        )
        .await?;
        Ok(row.map(|r| CategoryAccountsRow {
            method: r.get("method"),
            useful_life_months: r.get("useful_life_months"),
            fixed_asset_account_id: r.get("fixed_asset_account_id"),
            accumulated_depreciation_account_id: r.get("accumulated_depreciation_account_id"),
            depreciation_expense_account_id: r.get("depreciation_expense_account_id"),
            disposal_gain_loss_account_id: r.get("disposal_gain_loss_account_id"),
        }))
    }
}

backbone_core::impl_crud_repository!(AssetCategoryRepository, AssetCategory, soft_delete);
