//! Repository for Asset entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Asset, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Asset;

/// Table name for Asset entities
pub const TABLE_NAME: &str = "asset.assets";

/// Repository for Asset entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AssetRepository(
    backbone_orm::GenericCrudRepository<Asset, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AssetRepository {
    type Target = backbone_orm::GenericCrudRepository<Asset, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AssetRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(AssetRepository, Asset, soft_delete);
