//! Repository for Asset entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Asset SQL — the registration, the lifecycle's gated status transitions,
//! and the `FOR UPDATE` reads that serialize depreciation against disposal (4-layer rule: services
//! orchestrate and own the unit of work, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Asset, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Asset;

/// Table name for Asset entities
pub const TABLE_NAME: &str = "asset.assets";

/// Repository for Asset entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AssetRepository(
    backbone_orm::GenericCrudRepository<Asset, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AssetRepository {
    type Target = backbone_orm::GenericCrudRepository<Asset, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AssetRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an asset registration writes.
///
/// Mirrors the raw column shape rather than the `Asset` entity. Note the INSERT reuses `$10`/`$8` to
/// seed `accumulated_depreciation` = opening and `net_book_value` = gross − opening, so an onboarded
/// part-depreciated asset starts on the right book values.
pub struct NewAssetRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub asset_category_id: Uuid,
    pub asset_name: &'a str,
    pub asset_code: &'a str,
    pub item_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub gross_purchase_amount: Decimal,
    pub salvage_value: Decimal,
    pub opening_accumulated_depreciation: Decimal,
    pub useful_life_months: i32,
    pub purchase_date: chrono::DateTime<chrono::Utc>,
    pub available_for_use_date: Option<chrono::DateTime<chrono::Utc>>,
}

/// The asset's full lifecycle snapshot, as every verb reads it before deciding.
pub struct AssetSnapshotRow {
    pub company_id: Uuid,
    pub asset_category_id: Uuid,
    pub asset_code: String,
    pub gross_purchase_amount: Decimal,
    pub salvage_value: Decimal,
    pub useful_life_months: i32,
    pub purchase_date: chrono::DateTime<chrono::Utc>,
    pub available_for_use_date: Option<chrono::DateTime<chrono::Utc>>,
    pub accumulated_depreciation: Decimal,
    pub opening_accumulated_depreciation: Decimal,
    pub status: String,
}

/// The locked disposal projection — read UNDER the row lock, inside the disposal transaction.
pub struct DisposalLockRow {
    pub company_id: Uuid,
    pub asset_category_id: Uuid,
    pub asset_code: String,
    pub gross_purchase_amount: Decimal,
    pub accumulated_depreciation: Decimal,
    pub status: String,
}

/// Hand-written Asset SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl AssetRepository {
    /// Register an asset (draft).
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))`.
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to turn
    /// a duplicate asset code into a domain error.
    pub async fn insert_asset(&self, pool: &PgPool, a: &NewAssetRow<'_>) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO asset.assets
                     (id, company_id, asset_category_id, asset_name, asset_code, item_id, branch_id,
                      gross_purchase_amount, salvage_value, opening_accumulated_depreciation,
                      useful_life_months, purchase_date, available_for_use_date,
                      accumulated_depreciation, net_book_value, status)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$10,$8-$10,'draft'::asset_status)"#,
            )
            .bind(a.id).bind(a.company_id).bind(a.asset_category_id).bind(a.asset_name).bind(a.asset_code)
            .bind(a.item_id).bind(a.branch_id).bind(a.gross_purchase_amount).bind(a.salvage_value)
            .bind(a.opening_accumulated_depreciation).bind(a.useful_life_months).bind(a.purchase_date)
            .bind(a.available_for_use_date),
        )
        .await?;
        Ok(())
    }

    /// The asset's lifecycle snapshot. `Ok(None)` = not visible in the caller's scope.
    ///
    /// ID-only read: identified by the asset id alone — no company to scope from up front, so this rides
    /// the caller's scope (the request-dedicated connection under HTTP, or an event caller's
    /// `with_company_scope`). RLS fences it: another company's asset is simply not found. Callers read
    /// `company_id` off the returned row to bind their own tx.
    pub async fn find_snapshot(&self, pool: &PgPool, asset_id: Uuid) -> Result<Option<AssetSnapshotRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, asset_category_id, asset_code, gross_purchase_amount, salvage_value,
                          useful_life_months, purchase_date, available_for_use_date,
                          accumulated_depreciation, opening_accumulated_depreciation, status::text AS status
                   FROM asset.assets WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(asset_id),
        )
        .await?;
        Ok(row.map(|r| AssetSnapshotRow {
            company_id: r.get("company_id"),
            asset_category_id: r.get("asset_category_id"),
            asset_code: r.get("asset_code"),
            gross_purchase_amount: r.get("gross_purchase_amount"),
            salvage_value: r.get("salvage_value"),
            useful_life_months: r.get("useful_life_months"),
            purchase_date: r.get("purchase_date"),
            available_for_use_date: r.get("available_for_use_date"),
            accumulated_depreciation: r.get("accumulated_depreciation"),
            opening_accumulated_depreciation: r.get("opening_accumulated_depreciation"),
            status: r.get("status"),
        }))
    }

    /// Gate draft → active, stamping the available-for-use date. Returns rows affected (0 = already
    /// activated; the acquisition post deduped).
    ///
    /// Takes the CALLER'S connection so the status flip and the schedule inserts commit as one unit. The
    /// caller binds the asset's company on that connection (`bind_company_on`) — don't re-bind here.
    pub async fn claim_activation(
        &self,
        conn: &mut sqlx::PgConnection,
        asset_id: Uuid,
        available: chrono::DateTime<chrono::Utc>,
    ) -> Result<u64, sqlx::Error> {
        let moved = sqlx::query(
            r#"UPDATE asset.assets
               SET status='active'::asset_status, available_for_use_date=$2
               WHERE id=$1 AND status='draft'::asset_status"#,
        )
        .bind(asset_id)
        .bind(available)
        .execute(conn)
        .await?;
        Ok(moved.rows_affected())
    }

    /// Lock the asset row and read its status — the depreciation run's recheck.
    ///
    /// Takes the CALLER'S connection: this lock is held across the period's posted-gate, the GL post, and
    /// the asset advance. It is what serializes a depreciation period against `lock_for_disposal`, so a
    /// period can never credit Accum Dep after disposal.
    pub async fn lock_status(&self, conn: &mut sqlx::PgConnection, asset_id: Uuid) -> Result<String, sqlx::Error> {
        sqlx::query_scalar("SELECT status::text FROM asset.assets WHERE id=$1 FOR UPDATE")
            .bind(asset_id)
            .fetch_one(conn)
            .await
    }

    /// Advance the asset's accumulated depreciation / net book value; the last period flips it to
    /// `fully_depreciated`.
    ///
    /// Takes the CALLER'S connection — it must be the one holding the `lock_status` lock.
    pub async fn advance_depreciation(
        &self,
        conn: &mut sqlx::PgConnection,
        asset_id: Uuid,
        amount: Decimal,
        is_last: bool,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"UPDATE asset.assets
               SET accumulated_depreciation = accumulated_depreciation + $2,
                   net_book_value = gross_purchase_amount - (accumulated_depreciation + $2),
                   status = CASE WHEN $3 THEN 'fully_depreciated'::asset_status ELSE status END
               WHERE id=$1"#,
        )
        .bind(asset_id)
        .bind(amount)
        .bind(is_last)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Lock the asset row and read what the disposal needs — crucially `accumulated_depreciation` UNDER
    /// the lock. `Ok(None)` = not visible in the caller's scope.
    ///
    /// Takes the CALLER'S connection: the lock is held across the GL post + the status flip. A concurrent
    /// `run_depreciation` takes this same row lock (`lock_status`), so it cannot advance accumulated
    /// between this read and the disposal post — the Dr Accum Dep amount always matches what
    /// depreciation actually credited, and the asset nets off the books (council 2026-07-06).
    ///
    /// The caller cannot bind a company on that connection before this read: the company is only known
    /// FROM this row, read under the lock inside that very transaction. The caller binds the ambient
    /// scope instead — see `dispose_asset`.
    pub async fn lock_for_disposal(
        &self,
        conn: &mut sqlx::PgConnection,
        asset_id: Uuid,
    ) -> Result<Option<DisposalLockRow>, sqlx::Error> {
        let row = sqlx::query(
            r#"SELECT company_id, asset_category_id, asset_code, gross_purchase_amount,
                      accumulated_depreciation, status::text AS status
               FROM asset.assets WHERE id=$1 AND (metadata->>'deleted_at') IS NULL FOR UPDATE"#,
        )
        .bind(asset_id)
        .fetch_optional(conn)
        .await?;
        Ok(row.map(|r| DisposalLockRow {
            company_id: r.get("company_id"),
            asset_category_id: r.get("asset_category_id"),
            asset_code: r.get("asset_code"),
            gross_purchase_amount: r.get("gross_purchase_amount"),
            accumulated_depreciation: r.get("accumulated_depreciation"),
            status: r.get("status"),
        }))
    }

    /// Flip the asset to disposed. Takes the CALLER'S connection — it must be the one holding the
    /// `lock_for_disposal` lock, so the post and this flip commit together.
    pub async fn mark_disposed(&self, conn: &mut sqlx::PgConnection, asset_id: Uuid) -> Result<(), sqlx::Error> {
        sqlx::query("UPDATE asset.assets SET status='disposed'::asset_status WHERE id=$1")
            .bind(asset_id)
            .execute(conn)
            .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(AssetRepository, Asset, soft_delete);
