//! Repository for AssetDepreciationEntry entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written schedule SQL — the generated straight-line rows and the per-period
//! posted gate (4-layer rule: services orchestrate, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AssetDepreciationEntry, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::AssetDepreciationEntry;

/// Table name for AssetDepreciationEntry entities
pub const TABLE_NAME: &str = "asset.asset_depreciation_entries";

/// Repository for AssetDepreciationEntry entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AssetDepreciationEntryRepository(
    backbone_orm::GenericCrudRepository<AssetDepreciationEntry, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AssetDepreciationEntryRepository {
    type Target = backbone_orm::GenericCrudRepository<AssetDepreciationEntry, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AssetDepreciationEntryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row one generated schedule period writes.
///
/// Mirrors the raw column shape rather than the `AssetDepreciationEntry` entity. `accumulated_after` is
/// the FULL cumulative (it ends at the depreciable base) and `schedule_date` keeps the ORIGINAL period
/// offset — both computed by the caller so a mid-life onboarded asset's remaining periods tie out.
pub struct NewDepreciationEntryRow {
    pub id: Uuid,
    pub company_id: Uuid,
    pub asset_id: Uuid,
    pub period_no: i32,
    pub schedule_date: chrono::DateTime<chrono::Utc>,
    pub depreciation_amount: Decimal,
    pub accumulated_after: Decimal,
}

/// A schedule period that is due and not yet posted.
pub struct DueEntryRow {
    pub id: Uuid,
    pub period_no: i32,
    pub schedule_date: chrono::DateTime<chrono::Utc>,
    pub depreciation_amount: Decimal,
    pub accumulated_after: Decimal,
}

/// Hand-written AssetDepreciationEntry SQL. Lives here (not in the write service) per the module's
/// 4-layer rule.
impl AssetDepreciationEntryRepository {
    /// Insert one generated schedule period. Takes the CALLER'S connection so the whole schedule commits
    /// atomically with the draft→active flip. The caller has already bound the company — don't re-bind.
    pub async fn insert_entry(
        &self,
        conn: &mut sqlx::PgConnection,
        e: &NewDepreciationEntryRow,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO asset.asset_depreciation_entries
                 (id, company_id, asset_id, period_no, schedule_date, depreciation_amount,
                  accumulated_after, posted)
               VALUES ($1,$2,$3,$4,$5,$6,$7,false)"#,
        )
        .bind(e.id).bind(e.company_id).bind(e.asset_id).bind(e.period_no).bind(e.schedule_date)
        .bind(e.depreciation_amount).bind(e.accumulated_after)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Every unposted period due on or before `up_to`, in period order.
    ///
    /// A read outside any transaction: takes the pool and runs `fetch_all_rows_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company_id))` using the
    /// company read off the asset row — so this is correct for non-request callers (the depreciation
    /// job) too.
    pub async fn list_due(
        &self,
        pool: &PgPool,
        asset_id: Uuid,
        up_to: chrono::DateTime<chrono::Utc>,
    ) -> Result<Vec<DueEntryRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, period_no, schedule_date, depreciation_amount, accumulated_after
                   FROM asset.asset_depreciation_entries
                   WHERE asset_id=$1 AND posted=false AND schedule_date <= $2
                     AND (metadata->>'deleted_at') IS NULL
                   ORDER BY period_no ASC"#,
            )
            .bind(asset_id)
            .bind(up_to),
        )
        .await?;
        Ok(rows
            .iter()
            .map(|e| DueEntryRow {
                id: e.get("id"),
                period_no: e.get("period_no"),
                schedule_date: e.get("schedule_date"),
                depreciation_amount: e.get("depreciation_amount"),
                accumulated_after: e.get("accumulated_after"),
            })
            .collect())
    }

    /// Claim a period exactly once (CAS on `posted=false`) — the idempotence gate that makes a retry
    /// safe. Returns rows affected (0 = raced/retried; the caller skips it).
    ///
    /// Takes the CALLER'S connection: the claim, the GL post, and the asset advance are one unit of work
    /// under the asset's row lock. On any error the caller rolls back, leaving the period unposted for a
    /// clean retry.
    pub async fn claim_period(&self, conn: &mut sqlx::PgConnection, entry_id: Uuid) -> Result<u64, sqlx::Error> {
        let moved = sqlx::query(
            r#"UPDATE asset.asset_depreciation_entries SET posted=true, posted_at=now()
               WHERE id=$1 AND posted=false"#,
        )
        .bind(entry_id)
        .execute(conn)
        .await?;
        Ok(moved.rows_affected())
    }
}

backbone_core::impl_crud_repository!(AssetDepreciationEntryRepository, AssetDepreciationEntry, soft_delete);
