//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod asset_category_repository;
mod asset_repository;
mod asset_depreciation_entry_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use asset_category_repository::AssetCategoryRepository;
pub use asset_repository::AssetRepository;
pub use asset_depreciation_entry_repository::AssetDepreciationEntryRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written asset SQL's parameter/projection types (see the repositories declared `user_owned`
// in metaphor.codegen.yaml).
pub use asset_category_repository::{CategoryAccountsRow, NewAssetCategoryRow};
pub use asset_depreciation_entry_repository::{DueEntryRow, NewDepreciationEntryRow};
pub use asset_repository::{AssetSnapshotRow, DisposalLockRow, NewAssetRow};
// END CUSTOM
