//! Validator for AssetCategory entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AssetCategory>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::AssetCategory;

/// Validator type alias for AssetCategory entities.
pub type AssetCategoryValidator = EntityValidator<AssetCategory>;

/// Build a validator for AssetCategory with all schema-defined field rules.
pub fn asset_category_validator() -> AssetCategoryValidator {
    EntityValidator::new()
        .rule(RequiredString::new("category_name", |e: &AssetCategory| &e.category_name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
