//! Validator for Asset entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Asset>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::Asset;

/// Validator type alias for Asset entities.
pub type AssetValidator = EntityValidator<Asset>;

/// Build a validator for Asset with all schema-defined field rules.
pub fn asset_validator() -> AssetValidator {
    EntityValidator::new()
        .rule(RequiredString::new("asset_name", |e: &Asset| &e.asset_name))
        .rule(RequiredString::new("asset_code", |e: &Asset| &e.asset_code))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
