//! Validator for AssetDepreciationEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AssetDepreciationEntry>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::AssetDepreciationEntry;

/// Validator type alias for AssetDepreciationEntry entities.
pub type AssetDepreciationEntryValidator = EntityValidator<AssetDepreciationEntry>;

/// Build a validator for AssetDepreciationEntry with all schema-defined field rules.
pub fn asset_depreciation_entry_validator() -> AssetDepreciationEntryValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
