//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod asset_category_validator;
pub mod asset_validator;
pub mod asset_depreciation_entry_validator;

pub use asset_category_validator::{AssetCategoryValidator, asset_category_validator};
pub use asset_validator::{AssetValidator, asset_validator};
pub use asset_depreciation_entry_validator::{AssetDepreciationEntryValidator, asset_depreciation_entry_validator};

// <<< CUSTOM
// END CUSTOM
