//! Auth configuration for AssetCategory handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<AssetCategory>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AssetCategoryService;
use crate::domain::entity::AssetCategory;

/// Permission string constants for AssetCategory operations.
pub mod permissions {
    pub const LIST:        &str = "asset_category:list";
    pub const READ:        &str = "asset_category:read";
    pub const CREATE:      &str = "asset_category:create";
    pub const UPDATE:      &str = "asset_category:update";
    pub const DELETE:      &str = "asset_category:delete";
    pub const RESTORE:     &str = "asset_category:restore";
    pub const TRASH:       &str = "asset_category:trash";
    pub const EMPTY_TRASH: &str = "asset_category:empty_trash";
    pub const BULK_CREATE: &str = "asset_category:bulk_create";
    pub const UPSERT:      &str = "asset_category:upsert";
}

/// Resource policy for AssetCategory — maps CRUD actions to permission strings.
pub struct AssetCategoryPolicy;

#[async_trait]
impl ResourcePolicy<AssetCategory> for AssetCategoryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &AssetCategory,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for AssetCategory handlers.
///
/// Wraps `AssetCategoryService` and checks `AssetCategoryPolicy` before delegating.
pub type AssetCategoryGuard = PermissionGuard<AssetCategory>;

/// Service-integrated permission guard for AssetCategory (for use in generated handlers).
pub type AssetCategoryServiceGuard = ServicePermissionGuard<AssetCategory, AssetCategoryService, AssetCategoryPolicy>;

// <<< CUSTOM
// END CUSTOM
