//! Auth configuration for Asset handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Asset>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AssetService;
use crate::domain::entity::Asset;

/// Permission string constants for Asset operations.
pub mod permissions {
    pub const LIST:        &str = "asset:list";
    pub const READ:        &str = "asset:read";
    pub const CREATE:      &str = "asset:create";
    pub const UPDATE:      &str = "asset:update";
    pub const DELETE:      &str = "asset:delete";
    pub const RESTORE:     &str = "asset:restore";
    pub const TRASH:       &str = "asset:trash";
    pub const EMPTY_TRASH: &str = "asset:empty_trash";
    pub const BULK_CREATE: &str = "asset:bulk_create";
    pub const UPSERT:      &str = "asset:upsert";
}

/// Resource policy for Asset — maps CRUD actions to permission strings.
pub struct AssetPolicy;

#[async_trait]
impl ResourcePolicy<Asset> for AssetPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Asset,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Asset handlers.
///
/// Wraps `AssetService` and checks `AssetPolicy` before delegating.
pub type AssetGuard = PermissionGuard<Asset>;

/// Service-integrated permission guard for Asset (for use in generated handlers).
pub type AssetServiceGuard = ServicePermissionGuard<Asset, AssetService, AssetPolicy>;

// <<< CUSTOM
// END CUSTOM
