//! Auth configuration for AssetDepreciationEntry handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<AssetDepreciationEntry>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AssetDepreciationEntryService;
use crate::domain::entity::AssetDepreciationEntry;

/// Permission string constants for AssetDepreciationEntry operations.
pub mod permissions {
    pub const LIST:        &str = "asset_depreciation_entry:list";
    pub const READ:        &str = "asset_depreciation_entry:read";
    pub const CREATE:      &str = "asset_depreciation_entry:create";
    pub const UPDATE:      &str = "asset_depreciation_entry:update";
    pub const DELETE:      &str = "asset_depreciation_entry:delete";
    pub const RESTORE:     &str = "asset_depreciation_entry:restore";
    pub const TRASH:       &str = "asset_depreciation_entry:trash";
    pub const EMPTY_TRASH: &str = "asset_depreciation_entry:empty_trash";
    pub const BULK_CREATE: &str = "asset_depreciation_entry:bulk_create";
    pub const UPSERT:      &str = "asset_depreciation_entry:upsert";
}

/// Resource policy for AssetDepreciationEntry — maps CRUD actions to permission strings.
pub struct AssetDepreciationEntryPolicy;

#[async_trait]
impl ResourcePolicy<AssetDepreciationEntry> for AssetDepreciationEntryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &AssetDepreciationEntry,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for AssetDepreciationEntry handlers.
///
/// Wraps `AssetDepreciationEntryService` and checks `AssetDepreciationEntryPolicy` before delegating.
pub type AssetDepreciationEntryGuard = PermissionGuard<AssetDepreciationEntry>;

/// Service-integrated permission guard for AssetDepreciationEntry (for use in generated handlers).
pub type AssetDepreciationEntryServiceGuard = ServicePermissionGuard<AssetDepreciationEntry, AssetDepreciationEntryService, AssetDepreciationEntryPolicy>;

// <<< CUSTOM
// END CUSTOM
