//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod asset_category_auth;
pub mod asset_auth;
pub mod asset_depreciation_entry_auth;

pub use asset_category_auth::{AssetCategoryPolicy, AssetCategoryGuard, AssetCategoryServiceGuard};
pub use asset_auth::{AssetPolicy, AssetGuard, AssetServiceGuard};
pub use asset_depreciation_entry_auth::{AssetDepreciationEntryPolicy, AssetDepreciationEntryGuard, AssetDepreciationEntryServiceGuard};

// <<< CUSTOM
// END CUSTOM
