//! Asset API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Asset CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ASSET TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Asset
pub struct AssetTestData;

impl TestDataGenerator for AssetTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "asset_category_id": Uuid::new_v4().to_string(),
            "asset_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "asset_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "item_id": null,
            "branch_id": null,
            "gross_purchase_amount": 0,
            "salvage_value": 0,
            "useful_life_months": 1,
            "opening_accumulated_depreciation": 0,
            "purchase_date": now,
            "available_for_use_date": null,
            "accumulated_depreciation": 0,
            "net_book_value": 0,
            "status": "draft",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "asset_category_id": Uuid::new_v4().to_string(),
            "asset_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "asset_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "item_id": null,
            "branch_id": null,
            "gross_purchase_amount": 0,
            "salvage_value": 0,
            "useful_life_months": 1,
            "opening_accumulated_depreciation": 0,
            "purchase_date": now,
            "available_for_use_date": null,
            "accumulated_depreciation": 0,
            "net_book_value": 0,
            "status": "draft",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/asset_categories", &super::asset_category_api_test::AssetCategoryTestData).await {
            deps.push(("asset_category_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// ASSET API TEST
// ============================================================================

/// Asset API test suite
pub struct AssetApiTest {
    inner: GenericCrudTest<AssetTestData>,
}

impl AssetApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/assets", "Asset");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AssetTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AssetApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_asset_crud() {
        let mut test = AssetApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Asset specific tests here
// <<< CUSTOM TESTS END >>>
