//! AssetCategory API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the AssetCategory CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ASSETCATEGORY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for AssetCategory
pub struct AssetCategoryTestData;

impl TestDataGenerator for AssetCategoryTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "category_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "depreciation_method": "straight_line",
            "useful_life_months": 1,
            "fixed_asset_account_id": Uuid::new_v4().to_string(),
            "accumulated_depreciation_account_id": Uuid::new_v4().to_string(),
            "depreciation_expense_account_id": Uuid::new_v4().to_string(),
            "disposal_gain_loss_account_id": Uuid::new_v4().to_string(),
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "category_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "depreciation_method": "straight_line",
            "useful_life_months": 1,
            "fixed_asset_account_id": Uuid::new_v4().to_string(),
            "accumulated_depreciation_account_id": Uuid::new_v4().to_string(),
            "depreciation_expense_account_id": Uuid::new_v4().to_string(),
            "disposal_gain_loss_account_id": Uuid::new_v4().to_string(),
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ASSETCATEGORY API TEST
// ============================================================================

/// AssetCategory API test suite
pub struct AssetCategoryApiTest {
    inner: GenericCrudTest<AssetCategoryTestData>,
}

impl AssetCategoryApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/asset_categories", "AssetCategory");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AssetCategoryTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AssetCategoryApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_asset_category_crud() {
        let mut test = AssetCategoryApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add AssetCategory specific tests here
// <<< CUSTOM TESTS END >>>
