//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod asset_category_api_test;
pub mod asset_api_test;
pub mod asset_depreciation_entry_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use asset_category_api_test::*;
pub use asset_api_test::*;
pub use asset_depreciation_entry_api_test::*;
