//! Assets Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::AssetCategoryService;
use crate::application::service::AssetService;
use crate::application::service::AssetDepreciationEntryService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// AssetCategory service
    pub asset_category_service: Arc<AssetCategoryService>,
    /// Asset service
    pub asset_service: Arc<AssetService>,
    /// AssetDepreciationEntry service
    pub asset_depreciation_entry_service: Arc<AssetDepreciationEntryService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        asset_category_service: Arc<AssetCategoryService>,
        asset_service: Arc<AssetService>,
        asset_depreciation_entry_service: Arc<AssetDepreciationEntryService>
    ) -> Self {
        Self {
            asset_category_service,
            asset_service,
            asset_depreciation_entry_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::AssetsModule) -> Self {
        Self {
            asset_category_service: module.asset_category_service.clone(),
            asset_service: module.asset_service.clone(),
            asset_depreciation_entry_service: module.asset_depreciation_entry_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    asset_category_service: Option<Arc<AssetCategoryService>>,
    asset_service: Option<Arc<AssetService>>,
    asset_depreciation_entry_service: Option<Arc<AssetDepreciationEntryService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the AssetCategory service.
    pub fn with_asset_category_service(mut self, service: Arc<AssetCategoryService>) -> Self {
        self.asset_category_service = Some(service);
        self
    }

    /// Set the Asset service.
    pub fn with_asset_service(mut self, service: Arc<AssetService>) -> Self {
        self.asset_service = Some(service);
        self
    }

    /// Set the AssetDepreciationEntry service.
    pub fn with_asset_depreciation_entry_service(mut self, service: Arc<AssetDepreciationEntryService>) -> Self {
        self.asset_depreciation_entry_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            asset_category_service: self.asset_category_service.expect("asset_category_service is required"),
            asset_service: self.asset_service.expect("asset_service is required"),
            asset_depreciation_entry_service: self.asset_depreciation_entry_service.expect("asset_depreciation_entry_service is required"),
        }
    }
}
