//! Public events for Assets module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// ASSETCATEGORY EVENTS
// ============================================================================

/// Event published when a AssetCategory is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetCategoryCreatedEvent {
    pub id: AssetCategoryId,
    pub data: AssetCategoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AssetCategory is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetCategoryUpdatedEvent {
    pub id: AssetCategoryId,
    pub data: AssetCategoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AssetCategory is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetCategoryDeletedEvent {
    pub id: AssetCategoryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ASSET EVENTS
// ============================================================================

/// Event published when a Asset is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetCreatedEvent {
    pub id: AssetId,
    pub data: AssetDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Asset is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetUpdatedEvent {
    pub id: AssetId,
    pub data: AssetDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Asset is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetDeletedEvent {
    pub id: AssetId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ASSETDEPRECIATIONENTRY EVENTS
// ============================================================================

/// Event published when a AssetDepreciationEntry is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetDepreciationEntryCreatedEvent {
    pub id: AssetDepreciationEntryId,
    pub data: AssetDepreciationEntryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AssetDepreciationEntry is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetDepreciationEntryUpdatedEvent {
    pub id: AssetDepreciationEntryId,
    pub data: AssetDepreciationEntryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AssetDepreciationEntry is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetDepreciationEntryDeletedEvent {
    pub id: AssetDepreciationEntryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Assets module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AssetsEvent {
    AssetCategoryCreated(AssetCategoryCreatedEvent),
    AssetCategoryUpdated(AssetCategoryUpdatedEvent),
    AssetCategoryDeleted(AssetCategoryDeletedEvent),
    AssetCreated(AssetCreatedEvent),
    AssetUpdated(AssetUpdatedEvent),
    AssetDeleted(AssetDeletedEvent),
    AssetDepreciationEntryCreated(AssetDepreciationEntryCreatedEvent),
    AssetDepreciationEntryUpdated(AssetDepreciationEntryUpdatedEvent),
    AssetDepreciationEntryDeleted(AssetDepreciationEntryDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetsEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for AssetsEventMetadata {
    fn default() -> Self {
        Self {
            module: "assets",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
