//! Assets Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Assets exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use assets::exports::{AssetCategoryDto, AssetsQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `AssetCategoryDto` - Data transfer object for AssetCategory
/// - `AssetCategorySummary` - Summary view of AssetCategory
/// - `AssetCategoryId` - Type-safe ID wrapper
/// - `AssetDto` - Data transfer object for Asset
/// - `AssetSummary` - Summary view of Asset
/// - `AssetId` - Type-safe ID wrapper
/// - `AssetDepreciationEntryDto` - Data transfer object for AssetDepreciationEntry
/// - `AssetDepreciationEntrySummary` - Summary view of AssetDepreciationEntry
/// - `AssetDepreciationEntryId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `AssetsQueryService` - Read-only queries
///
/// ## Public Events
/// - `AssetCategoryCreatedEvent` - Published when AssetCategory is created
/// - `AssetCategoryUpdatedEvent` - Published when AssetCategory is updated
/// - `AssetCategoryDeletedEvent` - Published when AssetCategory is deleted
/// - `AssetCreatedEvent` - Published when Asset is created
/// - `AssetUpdatedEvent` - Published when Asset is updated
/// - `AssetDeletedEvent` - Published when Asset is deleted
/// - `AssetDepreciationEntryCreatedEvent` - Published when AssetDepreciationEntry is created
/// - `AssetDepreciationEntryUpdatedEvent` - Published when AssetDepreciationEntry is updated
/// - `AssetDepreciationEntryDeletedEvent` - Published when AssetDepreciationEntry is deleted
pub struct ExportSummary;
