//! Public services for Assets module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Assets module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait AssetsQueryService: Send + Sync {
    /// Get AssetCategory by ID
    async fn get_asset_category(&self, id: AssetCategoryId) -> Result<Option<AssetCategoryDto>>;

    /// Get AssetCategory summary by ID
    async fn get_asset_category_summary(&self, id: AssetCategoryId) -> Result<Option<AssetCategorySummary>>;

    /// Check if AssetCategory exists
    async fn asset_category_exists(&self, id: AssetCategoryId) -> Result<bool>;

    /// Get Asset by ID
    async fn get_asset(&self, id: AssetId) -> Result<Option<AssetDto>>;

    /// Get Asset summary by ID
    async fn get_asset_summary(&self, id: AssetId) -> Result<Option<AssetSummary>>;

    /// Check if Asset exists
    async fn asset_exists(&self, id: AssetId) -> Result<bool>;

    /// Get AssetDepreciationEntry by ID
    async fn get_asset_depreciation_entry(&self, id: AssetDepreciationEntryId) -> Result<Option<AssetDepreciationEntryDto>>;

    /// Get AssetDepreciationEntry summary by ID
    async fn get_asset_depreciation_entry_summary(&self, id: AssetDepreciationEntryId) -> Result<Option<AssetDepreciationEntrySummary>>;

    /// Check if AssetDepreciationEntry exists
    async fn asset_depreciation_entry_exists(&self, id: AssetDepreciationEntryId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of AssetsQueryService
pub struct AssetsQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> AssetsQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
