//! Assets Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AssetCategoryService;
pub use application::service::AssetService;
pub use application::service::AssetDepreciationEntryService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Assets module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let assets = AssetsModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = assets.all_crud_routes();
/// ```
pub struct AssetsModule {
    pub asset_category_service: Arc<AssetCategoryService>,
    pub asset_service: Arc<AssetService>,
    pub asset_depreciation_entry_service: Arc<AssetDepreciationEntryService>,
}

impl AssetsModule {
    /// Create a new module builder
    pub fn builder() -> AssetsModuleBuilder {
        AssetsModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_asset_category_routes,
            create_asset_routes,
            create_asset_depreciation_entry_routes,
        };

        Router::new()
            .merge(create_asset_category_routes(self.asset_category_service.clone()))
            .merge(create_asset_routes(self.asset_service.clone()))
            .merge(create_asset_depreciation_entry_routes(self.asset_depreciation_entry_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for AssetsModule
pub struct AssetsModuleBuilder {
    db_pool: Option<PgPool>,
}

impl AssetsModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<AssetsModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // AssetCategory service
        let asset_category_repository = Arc::new(AssetCategoryRepository::new(db_pool.clone()));
        let asset_category_service = Arc::new(AssetCategoryService::with_repository(asset_category_repository.clone()));

        // Asset service
        let asset_repository = Arc::new(AssetRepository::new(db_pool.clone()));
        let asset_service = Arc::new(AssetService::with_repository(asset_repository.clone()));

        // AssetDepreciationEntry service
        let asset_depreciation_entry_repository = Arc::new(AssetDepreciationEntryRepository::new(db_pool.clone()));
        let asset_depreciation_entry_service = Arc::new(AssetDepreciationEntryService::with_repository(asset_depreciation_entry_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(AssetsModule {
            asset_category_service,
            asset_service,
            asset_depreciation_entry_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for AssetsModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
