//! Assets Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
// <<< CUSTOM
// The module's published contract (DTOs, AssetsQueryService, events). Was emitted but never
// declared, so it compiled to nothing; declaring it makes the contract real.
pub mod exports;
// END CUSTOM

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AssetCategoryService;
pub use application::service::AssetService;
pub use application::service::AssetDepreciationEntryService;
// <<< CUSTOM
pub use application::service::{AssetEventSink, AssetWriteService, AssetsQueryServiceImpl, GlPostSink, LoggingSink};
// END CUSTOM

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

// <<< CUSTOM
use exports::AssetsQueryService;
use presentation::http::{create_asset_lifecycle_routes, AssetLifecycleState};
// END CUSTOM

/// Assets module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let assets = AssetsModule::builder()
///     .with_database(pool.clone())
///     .with_gl_sink(Arc::new(my_gl_adapter))
///     .build()?;
///
/// // Safe default (category CRUD + financial reads) merged with the validated
/// // lifecycle verbs — the only path that may change financial state:
/// let router = assets.all_crud_routes().merge(assets.lifecycle_routes());
/// ```
pub struct AssetsModule {
    pub(crate) asset_category_service: Arc<AssetCategoryService>,
    pub(crate) asset_service: Arc<AssetService>,
    pub(crate) asset_depreciation_entry_service: Arc<AssetDepreciationEntryService>,
    // <<< CUSTOM
    /// The validated, GL-backed lifecycle engine (activate / depreciate / dispose).
    pub(crate) asset_write_service: Arc<AssetWriteService>,
    /// The GL-posting sink a composing service supplies; required to mount lifecycle routes.
    pub(crate) gl_sink: Option<Arc<dyn GlPostSink>>,
    pub(crate) event_sink: Arc<dyn AssetEventSink>,
    /// The implemented published read contract for sibling modules.
    pub(crate) query: Arc<dyn AssetsQueryService>,
    // END CUSTOM
}

impl AssetsModule {
    /// Create a new module builder
    pub fn builder() -> AssetsModuleBuilder {
        AssetsModuleBuilder::new()
    }

    /// The default, **safe** route surface: full CRUD on the `AssetCategory`
    /// master, and **read-only** on the two engine-owned financial tables
    /// (`Asset`, `AssetDepreciationEntry`).
    ///
    /// The fixed-asset lifecycle — the only path permitted to write financial
    /// state — is mounted separately via [`Self::lifecycle_routes`] (register /
    /// activate / depreciate / dispose). Compose a real deployment as
    /// `all_crud_routes().merge(lifecycle_routes())`. Keeping the financial tables
    /// read-only here means generic mutation can never bypass the lifecycle
    /// engine's GL postings and silently desync the books from the ledger.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_asset_category_routes,
            create_asset_read_routes,
            create_asset_depreciation_entry_read_routes,
        };

        Router::new()
            .merge(create_asset_category_routes(self.asset_category_service.clone()))
            .merge(create_asset_read_routes(self.asset_service.clone()))
            .merge(create_asset_depreciation_entry_read_routes(
                self.asset_depreciation_entry_service.clone(),
            ))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but is really the safe default surface (category CRUD +
    /// financial reads). Prefer the explicit [`Self::all_crud_routes`] name and
    /// merge [`Self::lifecycle_routes`] for the write verbs.
    #[deprecated(note = "confusing alias; use all_crud_routes() (+ lifecycle_routes() for the write verbs)")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// The validated, GL-backed write surface — `register` / `activate` / `depreciate` /
    /// `dispose`. These are the only verbs permitted to change financial state.
    ///
    /// Requires a `GlPostSink` supplied via [`AssetsModuleBuilder::with_gl_sink`]; composing
    /// without one panics at startup (a wiring error, not a runtime condition).
    ///
    /// Compose a real deployment as `module.all_crud_routes().merge(module.lifecycle_routes())`.
    pub fn lifecycle_routes(&self) -> Router {
        let gl = self.gl_sink.clone().expect(
            "AssetsModule::lifecycle_routes() requires a GlPostSink — pass one via \
             AssetsModuleBuilder::with_gl_sink(...)",
        );
        let state = AssetLifecycleState {
            write_svc: self.asset_write_service.clone(),
            gl,
            event_sink: self.event_sink.clone(),
        };
        create_asset_lifecycle_routes(state)
    }

    /// The published read contract for sibling modules (the now-implemented
    /// [`AssetsQueryService`] over the module's DTOs).
    pub fn query_service(&self) -> Arc<dyn AssetsQueryService> {
        self.query.clone()
    }
}

/// Builder for AssetsModule
pub struct AssetsModuleBuilder {
    db_pool: Option<PgPool>,
    // <<< CUSTOM
    gl_sink: Option<Arc<dyn GlPostSink>>,
    event_sink: Option<Arc<dyn AssetEventSink>>,
    // END CUSTOM
}

impl AssetsModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
            // <<< CUSTOM
            gl_sink: None,
            event_sink: None,
            // END CUSTOM
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    /// Supply the GL-posting sink the lifecycle verbs post through (required to mount
    /// [`AssetsModule::lifecycle_routes`]). Assets owns no ledger, so a composing service
    /// adapts its accounting `PostingService` to [`GlPostSink`].
    pub fn with_gl_sink(mut self, sink: Arc<dyn GlPostSink>) -> Self {
        self.gl_sink = Some(sink);
        self
    }

    /// Supply the domain-event sink. Defaults to a logging sink if unset.
    pub fn with_event_sink(mut self, sink: Arc<dyn AssetEventSink>) -> Self {
        self.event_sink = Some(sink);
        self
    }
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<AssetsModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // AssetCategory service
        let asset_category_repository = Arc::new(AssetCategoryRepository::new(db_pool.clone()));
        let asset_category_service = Arc::new(AssetCategoryService::with_repository(asset_category_repository.clone()));

        // Asset service
        let asset_repository = Arc::new(AssetRepository::new(db_pool.clone()));
        let asset_service = Arc::new(AssetService::with_repository(asset_repository.clone()));

        // AssetDepreciationEntry service
        let asset_depreciation_entry_repository = Arc::new(AssetDepreciationEntryRepository::new(db_pool.clone()));
        let asset_depreciation_entry_service = Arc::new(AssetDepreciationEntryService::with_repository(asset_depreciation_entry_repository.clone()));

        // <<< CUSTOM
        let asset_write_service = Arc::new(AssetWriteService::new(db_pool.clone()));
        let event_sink: Arc<dyn AssetEventSink> =
            self.event_sink.unwrap_or_else(|| Arc::new(LoggingSink));
        let query: Arc<dyn AssetsQueryService> =
            Arc::new(AssetsQueryServiceImpl::new(db_pool.clone()));
        // END CUSTOM

        Ok(AssetsModule {
            asset_category_service,
            asset_service,
            asset_depreciation_entry_service,
            // <<< CUSTOM
            asset_write_service,
            gl_sink: self.gl_sink,
            event_sink,
            query,
            // END CUSTOM
        })
    }
}

impl Default for AssetsModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
