//! Use case type aliases for Asset aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAssetDto, UpdateAssetDto};
use crate::application::service::AssetService;
use crate::domain::entity::Asset;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAssetUseCase = CreateUseCase<Asset, CreateAssetDto, AssetService>;
pub type UpdateAssetUseCase = UpdateUseCase<Asset, UpdateAssetDto, AssetService>;
pub type GetAssetUseCase    = GetUseCase<Asset, AssetService>;
pub type DeleteAssetUseCase = DeleteUseCase<Asset, AssetService>;
pub type ListAssetUseCase   = ListUseCase<Asset, AssetService>;

// <<< CUSTOM
// END CUSTOM
