//! Use case type aliases for AssetDepreciationEntry aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAssetDepreciationEntryDto, UpdateAssetDepreciationEntryDto};
use crate::application::service::AssetDepreciationEntryService;
use crate::domain::entity::AssetDepreciationEntry;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAssetDepreciationEntryUseCase = CreateUseCase<AssetDepreciationEntry, CreateAssetDepreciationEntryDto, AssetDepreciationEntryService>;
pub type UpdateAssetDepreciationEntryUseCase = UpdateUseCase<AssetDepreciationEntry, UpdateAssetDepreciationEntryDto, AssetDepreciationEntryService>;
pub type GetAssetDepreciationEntryUseCase    = GetUseCase<AssetDepreciationEntry, AssetDepreciationEntryService>;
pub type DeleteAssetDepreciationEntryUseCase = DeleteUseCase<AssetDepreciationEntry, AssetDepreciationEntryService>;
pub type ListAssetDepreciationEntryUseCase   = ListUseCase<AssetDepreciationEntry, AssetDepreciationEntryService>;

// <<< CUSTOM
// END CUSTOM
