//! Use case type aliases for AssetCategory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAssetCategoryDto, UpdateAssetCategoryDto};
use crate::application::service::AssetCategoryService;
use crate::domain::entity::AssetCategory;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAssetCategoryUseCase = CreateUseCase<AssetCategory, CreateAssetCategoryDto, AssetCategoryService>;
pub type UpdateAssetCategoryUseCase = UpdateUseCase<AssetCategory, UpdateAssetCategoryDto, AssetCategoryService>;
pub type GetAssetCategoryUseCase    = GetUseCase<AssetCategory, AssetCategoryService>;
pub type DeleteAssetCategoryUseCase = DeleteUseCase<AssetCategory, AssetCategoryService>;
pub type ListAssetCategoryUseCase   = ListUseCase<AssetCategory, AssetCategoryService>;

// <<< CUSTOM
// END CUSTOM
