//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod asset_category_usecases;
pub mod asset_usecases;
pub mod asset_depreciation_entry_usecases;

pub use asset_category_usecases::{
    CreateAssetCategoryUseCase, UpdateAssetCategoryUseCase, GetAssetCategoryUseCase,
    DeleteAssetCategoryUseCase, ListAssetCategoryUseCase,
};
pub use asset_usecases::{
    CreateAssetUseCase, UpdateAssetUseCase, GetAssetUseCase,
    DeleteAssetUseCase, ListAssetUseCase,
};
pub use asset_depreciation_entry_usecases::{
    CreateAssetDepreciationEntryUseCase, UpdateAssetDepreciationEntryUseCase, GetAssetDepreciationEntryUseCase,
    DeleteAssetDepreciationEntryUseCase, ListAssetDepreciationEntryUseCase,
};

// <<< CUSTOM
// END CUSTOM
