//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod asset_category_handler;
pub mod asset_handler;
pub mod asset_depreciation_entry_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use asset_category_handler::{create_asset_category_routes, create_asset_category_read_routes, create_asset_category_write_routes};
pub use asset_handler::{create_asset_routes, create_asset_read_routes, create_asset_write_routes};
pub use asset_depreciation_entry_handler::{create_asset_depreciation_entry_routes, create_asset_depreciation_entry_read_routes, create_asset_depreciation_entry_write_routes};
// <<< CUSTOM
// END CUSTOM
